obj-y += source/elf.o
obj-y += source/eviction.o
obj-y += source/list.o
obj-y += source/page_set.o
obj-y += source/shm.o
obj-y += source/sort.o
obj-y += source/stats.o
obj-y += source/string.o
obj-y += source/termio.o
obj-y += source/tlb.o

obj-histogram-y += source/histogram.o
obj-histogram-pp-y += source/histogram-pp.o
obj-histogram-xp-y += source/histogram-xp.o

obj-aes-fr-y += source/aes-fr.o
obj-aes-ff-y += source/aes-ff.o
obj-aes-pp-y += source/aes-pp.o
obj-aes-pa-y += source/aes-pa.o
obj-aes-xp-y += source/aes-xp.o
obj-aes-xa-y += source/aes-xa.o

obj-count-y += source/count.o
obj-xfer-y += source/xfer.o
